apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - port: 8080
    name: http
  type: ClusterIP
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: mitin20/hello-spring-boot-image:0.0.1
        ports:
          - containerPort: 8080

        #adding some sizing
        resources:
          limits:
            cpu: "2"
            memory: 1536Mi
          requests:
            cpu: 200m
            memory: 1024Mi

    #     #Certs Configuration
    #     volumeMounts:
    #       - name: custom-cacerts
    #         mountPath: "/etc/ssl/certs/java/cacerts" #"/etc/ssl/certs/gsrsaovsslca2018.pem"#
    #         subPath: cacerts
    #         readOnly: false
    # #Certs Configuration
    # volumes:
    #   - name: custom-cacerts
    #     configMap:
    #       name: custom-cacerts


        #using env to connecto with mq db and more
        env:
          - name: JAVA_TOOL_OPTIONS
            value:
              -XX:MaxRAMPercentage=99.0 -XX:+UseContainerSupport -Dlogging.level.root=INFO
              -Dlogging.level.com.backbase=INFO
          - name: eureka.client.serviceUrl.defaultZone
            value: http://registry:8080/eureka/
          - name: EUREKA_INSTANCE_PREFERIPADDRESS
            value: "true"      
          - name: SIG_SECRET_KEY
            value: JWTSecretKeyDontUseInProduction!
          - name: EXTERNAL_SIG_SECRET_KEY
            value: JWTSecretKeyDontUseInProduction!
          - name: EXTERNAL_ENC_SECRET_KEY
            value: JWTEncKeyDontUseInProduction666!
          - name: USERCTX_KEY
            value: JWTSecretKeyDontUseInProduction!
          - name: SPRING_ACTIVEMQ_BROKER_URL
            value: tcp://backbase-env-activemq:61616
          - name: SPRING_ACTIVEMQ_USER
            value: admin
          - name: SPRING_ACTIVEMQ_PASSWORD
            value: "CHANGEME"
          - name: server.port
            value: "8080"
          - name: backbase.activemq.sslconfig
            value: "false"
          # - name: SPRING_DATASOURCE_URL
          #   value: "jdbc:sqlserver://sql-*.database.windows.net:1433;databaseName=db_ingestion_manager_dev"
          # - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          #   value: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
          # - name: SPRING_DATASOURCE_USERNAME
          #   valueFrom:
          #     secretKeyRef:
          #       key: username
          #       name: backbase-env-mssql
          # - name: SPRING_DATASOURCE_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       key: mysql-password
          #       name: backbase-env-mssql